disable-push=true
disable-publish=true
no-dev-version=true
consolidate-commits=true
pre-release-commit-message="release: variyak"
tag-prefix = "{{crate_name}}"
tag-message = "release {{version}}"
tag-name = "{{prefix}}-v{{version}}"
